version: '3.8'
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counterp
    volumes:
      - counterp_db_2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d counterp'"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: java -jar hwdockerapp.jar
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/counterp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"

volumes:
  counterp_db_2:
    external: true