spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/counterp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql